import type { ChatOptions, Conversation, Message } from './types.js';
import { models, skills } from './data/config.js';

export function genTitle(prompt: string) {
  const t = prompt.replace(/\s+/g, ' ').trim();
  return t.length > 16 ? `${t.slice(0, 16)}…` : t || '新对话';
}

export function defaultHistory(conv: Conversation): Message[] {
  return [
    { id: `${conv.id}-u`, role: 'user', content: conv.title, createdAt: conv.updatedAt },
    {
      id: `${conv.id}-a`, role: 'assistant', status: 'done', createdAt: conv.updatedAt,
      content: `这是关于「**${conv.title}**」的历史对话（mock 数据）。\n\n你可以继续在下方输入框追问，我会基于上下文继续回答。`,
    },
  ];
}

export function needSearch(prompt: string, opts: ChatOptions) {
  if (opts.mode === 'research') return true;
  if (/^(你好|hi|hello)/i.test(prompt.trim())) return false;
  return !['image', 'video', 'translate'].includes(opts.skill ?? '');
}

export function buildThinking(prompt: string): string {
  return `用户的问题是「${prompt.slice(0, 40)}」。\n先理解用户的真实意图，再判断需要哪些背景知识。\n可以从定义、要点、建议三个层次组织回答，并用表格帮助对比。\n最后检查回答是否准确、完整、易懂。`;
}

export function buildKeywords(prompt: string) {
  const kw = prompt.replace(/[，。？?！!,.]/g, ' ').trim().slice(0, 14);
  return [kw, `${kw.slice(0, 6)} 最新`];
}

export function buildReply(prompt: string, opts: ChatOptions): string {
  const modelName = models.find((m) => m.key === opts.model)?.name ?? 'Qwen';
  const p = prompt.trim();
  const skill = opts.skill;

  if (/^(你好|hi|hello|介绍)/i.test(p) || /你是谁|介绍一下你自己/.test(p)) {
    return `嗨，我是千问，阿里巴巴开发的 AI 助手～\n\n简单来说，我既能像百科全书一样回答各种问题，也能帮你处理工作和生活里的各种事——查信息、写文案、做 PPT、生成图片、整理录音纪要都能搞定。\n\n有什么想聊的，随时告诉我 😊`;
  }
  if (skill === 'image' || /画|图片|生图/.test(p)) {
    return `已根据你的描述生成图片：\n\n![mock image](https://picsum.photos/seed/${encodeURIComponent(p.slice(0, 8))}/640/400)\n\n如需调整风格、构图或比例，可以继续告诉我。`;
  }
  if (skill === 'video') {
    return `视频已生成（mock）：\n\n![mock video cover](https://picsum.photos/seed/v${encodeURIComponent(p.slice(0, 6))}/640/360)\n\n**画面描述**：${p}\n\n时长 5 秒 · 16:9 · 1080P`;
  }
  if (skill === 'ppt' || /ppt|汇报/i.test(p)) {
    return `### 📊 「${p}」PPT 大纲\n\n1. **封面**：标题 + 副标题 + 汇报人\n2. **背景与目标**：为什么做、要解决什么问题\n3. **现状分析**：关键数据与趋势图\n4. **核心方案**：3 个关键策略，每页一个\n5. **执行计划**：时间线与里程碑\n6. **风险与应对**\n7. **总结与展望**\n\n> 大纲确认后即可一键套用模板生成 PPT（mock 演示）。`;
  }
  if (skill === 'translate' || /翻译/.test(p)) {
    return `**译文：**\n\n${p.replace(/^翻译[:：]?/, '') || 'Hello, world!'}\n\nThis is a mock translation generated by ${modelName}.`;
  }
  if (skill === 'code' || /代码|python|排序|函数|bug|react|vue/i.test(p)) {
    return `### 📊 React vs Vue 核心对比\n\n| 维度 | React | Vue |\n| --- | --- | --- |\n| 设计定位 | 视图层库，强调函数式编程与单向数据流 | 渐进式框架，可按需扩展为全功能框架 |\n| 语法风格 | JSX（在 JavaScript 中写 HTML） | 单文件组件（.vue），模板语法接近 HTML |\n| 数据绑定 | 单向数据绑定，需手动调用 \`setState\` | 双向数据绑定（\`v-model\`），响应式自动追踪 |\n| 状态管理 | Redux、Zustand、Context 等 | 官方提供 Pinia，开箱即用 |\n| 学习曲线 | 较陡，需掌握 Hooks 心智模型 | 平缓，官方文档完善 |\n\n### 代码示例：计数器\n\n\`\`\`tsx\nimport { useState } from 'react';\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(count + 1)}>点击了 {count} 次</button>;\n}\n\`\`\`\n\n\`\`\`vue\n<script setup>\nimport { ref } from 'vue';\nconst count = ref(0);\n</script>\n\n<template>\n  <button @click="count++">点击了 {{ count }} 次</button>\n</template>\n\`\`\`\n\n**总结**：追求灵活与生态选 React，追求上手快与开发效率选 Vue。`;
  }

  const skillName = skills.find((s) => s.key === skill)?.name;
  return `关于「${p}」，我从以下几个方面为你梳理${skillName ? `（${skillName}）` : ''}：\n\n### 一、核心要点\n1. **明确目标**：先搞清楚最想解决的问题是什么\n2. **拆解步骤**：把大问题拆成可执行的小任务\n3. **持续迭代**：根据反馈不断调整\n\n### 二、具体建议\n- 从最简单、见效最快的环节入手\n- 记录过程中的数据，方便复盘\n- 必要时寻求专业人士或工具的帮助\n\n### 三、总结\n\n| 阶段 | 重点 |\n| --- | --- |\n| 准备 | 收集信息、设定目标 |\n| 执行 | 小步快跑、及时反馈 |\n| 复盘 | 总结经验、优化方法 |\n\n以上内容由 **${modelName}** 生成（mock 数据），欢迎继续追问～`;
}

export function snippetOf(content: string, keyword: string) {
  const plain = content.replace(/[#*`>|\-]/g, '').replace(/\s+/g, ' ');
  const i = plain.toLowerCase().indexOf(keyword.toLowerCase());
  if (i < 0) return undefined;
  const start = Math.max(0, i - 12);
  return `${start > 0 ? '…' : ''}${plain.slice(start, i + keyword.length + 30)}`;
}
